[package]
name = "barbirolli"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["linux"]
linux = ["dep:fctools", "dep:nlink", "dep:rustix"]

[dependencies]
dashmap.workspace = true
fctools = { workspace = true, features = [
    "direct-process-spawner",
    "tokio-runtime",
    "unrestricted-vmm-executor",
    "vm",
], optional = true }
nlink = { workspace = true, features = ["tuntap"], optional = true }
rustix = { version = "1.0.5", default-features = false, features = ["process"], optional = true }
serde.workspace = true
serde_json.workspace = true
ssh-key.workspace = true
derive_more = { version = "2.1.1", features = ["full"] }
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
barbirolli_derive.workspace = true
