[package]
name = "barbirolli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
derive_more = { version = "2.1.1", features = ["full"] }
futures.workspace = true
nonempty-collections.workspace = true
serde.workspace = true
ssh-key.workspace = true
thiserror.workspace = true
validated.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
dashmap.workspace = true
fctools = { workspace = true, features = [
    "direct-process-spawner",
    "tokio-runtime",
    "unrestricted-vmm-executor",
    "vm",
    "metrics-extension",
    "rustix-syscall-backend",
]}
loopdev = { package = "loopdev-3", version = "0.5.3" }
nlink = { workspace = true, features = ["tuntap"] }
rustix = { version = "1.0.5", default-features = false, features = ["mount", "process"] }
serde_json.workspace = true
tempfile.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
barbirolli_derive.workspace = true
reqwest.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tokio.workspace = true
