[package]
name = "elhone"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "The HTTP API for Barbirolli-managed microVMs and OCI images"
repository.workspace = true
readme = "README.md"
categories = ["web-programming::http-server"]
keywords = ["firecracker", "microvm", "axum", "oci"]
rust-version.workspace = true

[dependencies]
axum.workspace = true
barbirolli.workspace = true
dashmap.workspace = true
derive_more.workspace = true
flate2.workspace = true
futures.workspace = true
oci-spec.workspace = true
reqwest = { workspace = true, features = ["json", "rustls-no-provider", "stream"] }
rustls.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tar.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
zstd.workspace = true

[dev-dependencies]
http-body-util.workspace = true
tower.workspace = true
xattr.workspace = true
