no_default_features = true
test_workspace = true

examine_re = [
  "is_authorized_key",
  "VmStore::",
  "NetworkSpec::",
  "Barbirolli::(create|list|status|spec|authorized_keys_path|ssh_address|start|shutdown|delete|shutdown_all)",
  "BarbirolliVm::",
  "ManagedVm::",
]
